apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: myphp
  name: myphp
  namespace: default
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'myphp:latest'
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      ref: master
      uri: 'https://github.com/wipas-p/myPhp.git'
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: 'php:latest'
        namespace: openshift
    type: Source
